GET http://localhost:4000/rotiseria/venta/day/2025-07-31

POST http://localhost:3000/rotiseria/venta
Content-Type: application/json

{
  "id": 1,
  "fecha": "2023-10-01",
  "idCliente": 1,
  "cliente": "A Consumidor Final",
  "tipo_venta": "CD",
  "tipo_comp": "Comprobante",
  "F": false,
  "listaProductos": [
        {
          "cantidad": 2,
            "_id": 1,
            "nombre": "Pollo Asado",
            "precio": 10.0
        }
    
  ],
  "precio": 125.0
}